services:
  - type: web
    name: messagemind-api
    runtime: node
    rootDir: backend
    startCommand: npm start
    buildCommand: npm install && npm run build
    envVars:
      - key: NODE_ENV
        value: production
